/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banka;

/**
 *
 * @author malia
 */
public class BankaciSistem extends javax.swing.JFrame {

    /**
     * Creates new form BankaciSistem
     */
    public BankaciSistem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BankaciSistemParaYatırma = new javax.swing.JButton();
        BankaciSistemYeniMusteri = new javax.swing.JButton();
        BankaciSistemMusteriDuzenle = new javax.swing.JButton();
        BankaciSistemParaCekme = new javax.swing.JButton();
        BankaciSistemMusteriSil = new javax.swing.JButton();
        BankaciSistemHesapAc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BankaciSistemParaYatırma.setText("PARA YATIRMA");
        BankaciSistemParaYatırma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankaciSistemParaYatırmaActionPerformed(evt);
            }
        });

        BankaciSistemYeniMusteri.setText("YENİ MÜŞTERİ");
        BankaciSistemYeniMusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankaciSistemYeniMusteriActionPerformed(evt);
            }
        });

        BankaciSistemMusteriDuzenle.setText("MÜŞTERİ DÜZENLE");
        BankaciSistemMusteriDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankaciSistemMusteriDuzenleActionPerformed(evt);
            }
        });

        BankaciSistemParaCekme.setText("PARA ÇEKME");
        BankaciSistemParaCekme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankaciSistemParaCekmeActionPerformed(evt);
            }
        });

        BankaciSistemMusteriSil.setText("MÜŞTERİ SİL");
        BankaciSistemMusteriSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankaciSistemMusteriSilActionPerformed(evt);
            }
        });

        BankaciSistemHesapAc.setText("HESAP AÇ");
        BankaciSistemHesapAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankaciSistemHesapAcActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BANKACI");

        jButton1.setText("İPTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BankaciSistemYeniMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BankaciSistemMusteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BankaciSistemParaYatırma, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BankaciSistemParaCekme, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BankaciSistemMusteriDuzenle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BankaciSistemHesapAc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jButton1)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankaciSistemYeniMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankaciSistemMusteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankaciSistemMusteriDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankaciSistemHesapAc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankaciSistemParaYatırma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankaciSistemParaCekme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BankaciSistemYeniMusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankaciSistemYeniMusteriActionPerformed
        // TODO add your handling code here:
        YeniMusteri yeniMusteri = new YeniMusteri();
        yeniMusteri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BankaciSistemYeniMusteriActionPerformed

    private void BankaciSistemMusteriSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankaciSistemMusteriSilActionPerformed
        // TODO add your handling code here:
        MusteriSil musteriSil = new MusteriSil();
        musteriSil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BankaciSistemMusteriSilActionPerformed

    private void BankaciSistemHesapAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankaciSistemHesapAcActionPerformed
        // TODO add your handling code here:
        YeniHesapGiris yeniHesapGiris = new YeniHesapGiris();
        yeniHesapGiris.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BankaciSistemHesapAcActionPerformed

    private void BankaciSistemMusteriDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankaciSistemMusteriDuzenleActionPerformed
        // TODO add your handling code here:
        MusteriDuzenle musteriDuzenle = new MusteriDuzenle();
        musteriDuzenle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BankaciSistemMusteriDuzenleActionPerformed

    private void BankaciSistemParaYatırmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankaciSistemParaYatırmaActionPerformed
        // TODO add your handling code here:
        BankaciParaYatir paraYatir = new BankaciParaYatir();
        paraYatir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BankaciSistemParaYatırmaActionPerformed

    private void BankaciSistemParaCekmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankaciSistemParaCekmeActionPerformed
        // TODO add your handling code here:
        BankaciParaCekGiris paraCekGiris = new BankaciParaCekGiris();
        paraCekGiris.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BankaciSistemParaCekmeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Panel panel = new Panel();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankaciSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankaciSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankaciSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankaciSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankaciSistem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BankaciSistemHesapAc;
    private javax.swing.JButton BankaciSistemMusteriDuzenle;
    private javax.swing.JButton BankaciSistemMusteriSil;
    private javax.swing.JButton BankaciSistemParaCekme;
    private javax.swing.JButton BankaciSistemParaYatırma;
    private javax.swing.JButton BankaciSistemYeniMusteri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
