/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banka;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author malia
 */
public class BankaciDuzenle extends javax.swing.JFrame {

    /**
     * Creates new form BankaciDuzenle
     */
    public BankaciDuzenle() {
        initComponents();
    }

    
    public ArrayList<Bankaci> bankaciList(){
        ArrayList<Bankaci> bankaciList = new ArrayList<>();
        try{
            Connection conx = ConnectionProvider.baglan();
            String sql = "SELECT * FROM bankaci";
            Statement st = conx.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Bankaci bankaci; 
           while(rs.next()){
               bankaci = new Bankaci(rs.getString("bankaciTc"),rs.getString("bankaciAd"),rs.getString("bankaciSoyad"),rs.getString("bankaciSifre"));
               bankaciList.add(bankaci);
           }
        }
        catch(Exception ex){
            
        }
        return bankaciList;
 
    }
    public void show_bankaci(){
        ArrayList<Bankaci> list = bankaciList();
        DefaultTableModel model = (DefaultTableModel)BankaciDuzenleTablo.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getBankaciTC();
            row[1] = list.get(i).getBankaciAd();
            row[2] = list.get(i).getBankaciSoyad();
            row[3] = list.get(i).getBankaciSifre();
            model.addRow(row);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bankaciDuzenleIsim = new javax.swing.JTextField();
        bankaciDuzenleSoyisim = new javax.swing.JTextField();
        bankaciDuzenleSifre = new javax.swing.JTextField();
        bankaciDuzenleOnayla = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bankaciDuzenleTc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BankaciDuzenleTablo = new javax.swing.JTable();
        BankaciDuzenleKayitlar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BANKACI DÜZENLE");

        jLabel2.setText("İsim:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Soyisim:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Yeni Şifre:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bankaciDuzenleIsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaciDuzenleIsimActionPerformed(evt);
            }
        });

        bankaciDuzenleSoyisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaciDuzenleSoyisimActionPerformed(evt);
            }
        });

        bankaciDuzenleSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaciDuzenleSifreActionPerformed(evt);
            }
        });

        bankaciDuzenleOnayla.setText("Onayla");
        bankaciDuzenleOnayla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaciDuzenleOnaylaActionPerformed(evt);
            }
        });

        jButton1.setText("İptal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Var olan TC:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bankaciDuzenleTc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankaciDuzenleTcActionPerformed(evt);
            }
        });

        BankaciDuzenleTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC", "İsim", "Soyisim", "Şifre"
            }
        ));
        BankaciDuzenleTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BankaciDuzenleTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BankaciDuzenleTablo);

        BankaciDuzenleKayitlar.setText("Kayıtlar");
        BankaciDuzenleKayitlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankaciDuzenleKayitlarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankaciDuzenleIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankaciDuzenleSoyisim, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankaciDuzenleSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankaciDuzenleTc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(bankaciDuzenleOnayla)
                        .addGap(18, 18, 18)
                        .addComponent(BankaciDuzenleKayitlar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankaciDuzenleTc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankaciDuzenleIsim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankaciDuzenleSoyisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankaciDuzenleSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(bankaciDuzenleOnayla)
                            .addComponent(BankaciDuzenleKayitlar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankaciDuzenleIsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaciDuzenleIsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankaciDuzenleIsimActionPerformed

    private void bankaciDuzenleSoyisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaciDuzenleSoyisimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankaciDuzenleSoyisimActionPerformed

    private void bankaciDuzenleSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaciDuzenleSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankaciDuzenleSifreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MudurSistem mudurSistem = new MudurSistem();
        mudurSistem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bankaciDuzenleOnaylaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaciDuzenleOnaylaActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection conx = ConnectionProvider.baglan();
            int row = BankaciDuzenleTablo.getSelectedRow();
            String value = (BankaciDuzenleTablo.getModel().getValueAt(row, 0).toString());
            String sql = ("UPDATE bankaci SET bankaciAd = ?, bankaciSoyad= ?, bankaciSifre = ? WHERE bankaciTc = ?")+value;
            PreparedStatement pst =conx.prepareStatement(sql);
            //pst.setString(1, bankaciDuzenleTC.getText());
            pst.setString(1, bankaciDuzenleIsim.getText());        
            pst.setString(2, bankaciDuzenleSoyisim.getText());   
            pst.setString(3, bankaciDuzenleSifre.getText());  
            pst.setString(4, bankaciDuzenleTc.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) BankaciDuzenleTablo.getModel();
            model.setRowCount(0);
            show_bankaci(); 
            JOptionPane.showMessageDialog(null, "Başarılı");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
        
        
        
        /*
        try{
            Connection conx = ConnectionProvider.baglan();
            Statement st = conx.createStatement();
            //BankaciDuzenleGiris bdg = new BankaciDuzenleGiris();
            String sql = ("UPDATE bankaci SET bankaciAd = ?, bankaciSoyad= ?, bankaciSifre = ? WHERE bankaciTc = ?");
            PreparedStatement pst =conx.prepareStatement(sql);
            //pst.setString(1, bankaciDuzenleTC.getText());
            pst.setString(1, bankaciDuzenleIsim.getText());        
            pst.setString(2, bankaciDuzenleSoyisim.getText());   
            pst.setString(3, bankaciDuzenleSifre.getText());  
            pst.setString(4, bankaciDuzenleTc.getText());
            //st.executeUpdate(sql);
            int rs = pst.executeUpdate();
            pst.executeUpdate();
            pst.close();
            
            if(rs == 1){
                JOptionPane.showMessageDialog(null, "BAŞARILI");
                MudurSistem mudurSistem = new MudurSistem();
                mudurSistem.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "HATALI T.C. NO");
                //bankaciDuzenle.setText("");
                //bankaciSifreGiris.setText("");
            }
            conx.close(); 
            
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, "BAŞARISIZ");
            //JOptionPane.showMessageDialog(null, ex);
            }*/
    }//GEN-LAST:event_bankaciDuzenleOnaylaActionPerformed

    private void bankaciDuzenleTcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankaciDuzenleTcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankaciDuzenleTcActionPerformed

    private void BankaciDuzenleKayitlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankaciDuzenleKayitlarActionPerformed
        // TODO add your handling code here:
       show_bankaci();
    }//GEN-LAST:event_BankaciDuzenleKayitlarActionPerformed

    private void BankaciDuzenleTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BankaciDuzenleTabloMouseClicked
        // TODO add your handling code here:
        String BankaciAdi = bankaciDuzenleIsim.getSelectedText();
        String BankaciSifre = bankaciDuzenleSifre.getText();
        String BankaciSoyadi = bankaciDuzenleSoyisim.getText();
        String BankaciID = bankaciDuzenleTc.getText();
        int i = BankaciDuzenleTablo.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)BankaciDuzenleTablo.getModel();
        BankaciID.setText(model.getValueAt(i,1).toString());
        BankaciSifre.setText(model.getValueAt(i,2).toString());
        BankaciAdi.setText(model.getValueAt(i,3).toString());
        BankaciSoyadi.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_BankaciDuzenleTabloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankaciDuzenle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BankaciDuzenleKayitlar;
    private javax.swing.JTable BankaciDuzenleTablo;
    private javax.swing.JTextField bankaciDuzenleIsim;
    private javax.swing.JButton bankaciDuzenleOnayla;
    private javax.swing.JTextField bankaciDuzenleSifre;
    private javax.swing.JTextField bankaciDuzenleSoyisim;
    private javax.swing.JTextField bankaciDuzenleTc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
