/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banka;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author malia
 */
public class MusteriHesapDetayGiris extends javax.swing.JFrame {

    /**
     * Creates new form MusteriHesapDetayGiris
     */
    public MusteriHesapDetayGiris() {
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MusteriHesapDetayGirisBakiye = new javax.swing.JTextField();
        HesapNoGiris = new javax.swing.JLabel();
        MusteriHesapDetayGirisNo = new javax.swing.JTextField();
        MusteriHesapDetayGirisOnayla = new javax.swing.JButton();
        MusteriHesapDetayGirisIptal = new javax.swing.JButton();
        HesapDetayBakiye = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        MusteriHesapDetayGirisBakiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriHesapDetayGirisBakiyeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HesapNoGiris.setText("Hesap No:");

        MusteriHesapDetayGirisNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriHesapDetayGirisNoActionPerformed(evt);
            }
        });

        MusteriHesapDetayGirisOnayla.setText("Onayla");
        MusteriHesapDetayGirisOnayla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriHesapDetayGirisOnaylaActionPerformed(evt);
            }
        });

        MusteriHesapDetayGirisIptal.setText("İptal");
        MusteriHesapDetayGirisIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriHesapDetayGirisIptalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HESAP DETAY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(HesapDetayBakiye, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(HesapNoGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MusteriHesapDetayGirisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(MusteriHesapDetayGirisIptal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MusteriHesapDetayGirisOnayla)))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HesapDetayBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusteriHesapDetayGirisNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HesapNoGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusteriHesapDetayGirisIptal)
                    .addComponent(MusteriHesapDetayGirisOnayla))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MusteriHesapDetayGirisNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriHesapDetayGirisNoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MusteriHesapDetayGirisNoActionPerformed

    private void MusteriHesapDetayGirisOnaylaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriHesapDetayGirisOnaylaActionPerformed
        // TODO add your handling code here:
        String hesapNo = MusteriHesapDetayGirisNo.getText();
        try{
            Connection conx = ConnectionProvider.baglan();
            Statement st = conx.createStatement();
            
            String sql = ("SELECT * FROM hesap WHERE hesapID = ?");
            String sql2 = ("SELECT hesapBakiye FROM hesap WHERE hesapID = ?");
            PreparedStatement pst =conx.prepareStatement(sql);
            pst.setString(1, hesapNo);
            //String duzenleTc = bankaciDuzenleGirisTC.getText();
            
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                //JOptionPane.showMessageDialog(null, "BAŞARILI");
                /*MusteriHesapDetay musteriHesapDetay = new MusteriHesapDetay();
                musteriHesapDetay.setVisible(true);
                this.setVisible(false);*/
                JOptionPane.showMessageDialog(null, "Bakiye: "+rs.getString("hesapBakiye"));
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Böyle bir hesap bulunmamaktadır!");
              //  bankaciTcGiris.setText("");
               // bankaciSifreGiris.setText("");
            }
            conx.close(); 
            
            }
            catch(Exception ex)
            {
            JOptionPane.showMessageDialog(null, ex);
            }
        
        
        
    }//GEN-LAST:event_MusteriHesapDetayGirisOnaylaActionPerformed

    private void MusteriHesapDetayGirisIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriHesapDetayGirisIptalActionPerformed
        // TODO add your handling code here:
        MusteriSistem musteriSistem = new MusteriSistem();
        musteriSistem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusteriHesapDetayGirisIptalActionPerformed

    private void MusteriHesapDetayGirisBakiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriHesapDetayGirisBakiyeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_MusteriHesapDetayGirisBakiyeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriHesapDetayGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriHesapDetayGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriHesapDetayGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriHesapDetayGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriHesapDetayGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HesapDetayBakiye;
    private javax.swing.JLabel HesapNoGiris;
    private javax.swing.JTextField MusteriHesapDetayGirisBakiye;
    private javax.swing.JButton MusteriHesapDetayGirisIptal;
    private javax.swing.JTextField MusteriHesapDetayGirisNo;
    private javax.swing.JButton MusteriHesapDetayGirisOnayla;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
