/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banka;

/**
 *
 * @author malia
 */
public class MusteriSistem extends javax.swing.JFrame {

    /**
     * Creates new form MusteriSistem
     */
    public MusteriSistem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MusteriSistemHesapDetay = new javax.swing.JButton();
        MusteriSistemKrediBasvuru = new javax.swing.JButton();
        MusteriSistemKrediSonucu = new javax.swing.JButton();
        MusteriSistemParaYatirma = new javax.swing.JButton();
        MusteriSistemParaCekme = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MÜŞTERİ ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MusteriSistemHesapDetay.setText("HESAP DETAY");
        MusteriSistemHesapDetay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriSistemHesapDetayActionPerformed(evt);
            }
        });

        MusteriSistemKrediBasvuru.setText("KREDİ BAŞVURU");
        MusteriSistemKrediBasvuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriSistemKrediBasvuruActionPerformed(evt);
            }
        });

        MusteriSistemKrediSonucu.setText("KREDİ SONUCU");
        MusteriSistemKrediSonucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriSistemKrediSonucuActionPerformed(evt);
            }
        });

        MusteriSistemParaYatirma.setText("PARA YATIRMA");
        MusteriSistemParaYatirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriSistemParaYatirmaActionPerformed(evt);
            }
        });

        MusteriSistemParaCekme.setText("PARA ÇEKME");
        MusteriSistemParaCekme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriSistemParaCekmeActionPerformed(evt);
            }
        });

        jButton1.setText("İPTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 67, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MusteriSistemKrediBasvuru, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MusteriSistemHesapDetay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MusteriSistemParaYatirma, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MusteriSistemParaCekme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(MusteriSistemKrediSonucu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusteriSistemHesapDetay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MusteriSistemParaYatirma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusteriSistemKrediBasvuru, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MusteriSistemParaCekme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MusteriSistemKrediSonucu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MusteriSistemHesapDetayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriSistemHesapDetayActionPerformed
        // TODO add your handling code here:
        MusteriHesapDetayGiris musteriHesapDetay = new MusteriHesapDetayGiris();
        musteriHesapDetay.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusteriSistemHesapDetayActionPerformed

    private void MusteriSistemParaYatirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriSistemParaYatirmaActionPerformed
        // TODO add your handling code here:
        BankaciParaYatir paraYatir = new BankaciParaYatir();
        paraYatir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusteriSistemParaYatirmaActionPerformed

    private void MusteriSistemKrediBasvuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriSistemKrediBasvuruActionPerformed
        // TODO add your handling code here:
        MusteriKrediBasvuru musteriKrediBasvuru = new MusteriKrediBasvuru();
        musteriKrediBasvuru.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusteriSistemKrediBasvuruActionPerformed

    private void MusteriSistemParaCekmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriSistemParaCekmeActionPerformed
        // TODO add your handling code here:
        BankaciParaCek paraCek = new BankaciParaCek();
        paraCek.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusteriSistemParaCekmeActionPerformed

    private void MusteriSistemKrediSonucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriSistemKrediSonucuActionPerformed
        // TODO add your handling code here:
        MusteriKrediSonucu musteriKrediSonucu = new MusteriKrediSonucu();
        musteriKrediSonucu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusteriSistemKrediSonucuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Panel panel = new Panel();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriSistem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MusteriSistemHesapDetay;
    private javax.swing.JButton MusteriSistemKrediBasvuru;
    private javax.swing.JButton MusteriSistemKrediSonucu;
    private javax.swing.JButton MusteriSistemParaCekme;
    private javax.swing.JButton MusteriSistemParaYatirma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
